name: ROS CNIP list

on:
  schedule:
    - cron: "00 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
        
    - name: Set git identity
      run : |
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --global user.name "github-actions[bot]"
        sudo timedatectl set-timezone "Asia/Shanghai"
     
    - name: Combine
      run: |
        qqwry="$(curl -kLfsm 5 https://raw.githubusercontent.com/metowolf/iplist/master/data/special/china.txt)"
        ipipnet="$(curl -kLfsm 5 https://raw.githubusercontent.com/17mon/china_ip_list/master/china_ip_list.txt)"
        clang="$(curl -kLfsm 5 https://ispip.clang.cn/all_cn_cidr.txt)"
        echo "$qqwry\n$ipipnet\n$clang" > cnip.rsc
        awk '!seen[$0]++' cnip.rsc
        iplist=$(cat cnip.rsc)
        echo -e "${iplist}" | sed -e 's/^/add address=/g' -e 's/$/ list=china-ip/g' | sed -e $'1i\\\n/ip firewall address-list' -e $'1i\\\nremove [find list=china-ip]' > cnip.rsc

    - name: Apply
      run: |
        Emoji=("🎉" "🤞" "✨" "🎁" "🎈" "🎄" "🎨" "💋" "🍓" "🍕" "🍉" "💐" "🌴" "🚀" "🛸" "🗽" "⛅" "🌈" "🔥" "⛄" "🐶" "🏅" "🦄" "🐤")
        git add .
        git commit -m "${Emoji[$[$RANDOM % ${#Emoji[@]}]]} Sync $(date +%Y-%m-%d"  "%H:%M:%S)"
        git push -f
